<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260708170343 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create baseline catalog and inventory schema.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS catalog_categories (id UUID NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_8fd9b4b3989d9b62 ON catalog_categories (slug)');

        $this->addSql('CREATE TABLE IF NOT EXISTS catalog_products (id UUID NOT NULL, category_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, stock INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sku VARCHAR(20) NOT NULL, price_amount INT NOT NULL, price_currency VARCHAR(3) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE catalog_products ADD COLUMN IF NOT EXISTS category_id UUID DEFAULT NULL');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_816d844412469de2 ON catalog_products (category_id)');
        $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_816d844412469de2'
    ) THEN
        ALTER TABLE catalog_products
            ADD CONSTRAINT fk_816d844412469de2
            FOREIGN KEY (category_id)
            REFERENCES catalog_categories (id)
            ON DELETE SET NULL
            NOT DEFERRABLE INITIALLY IMMEDIATE;
    END IF;
END
$$;
SQL);

        $this->addSql('CREATE TABLE IF NOT EXISTS inventory_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id VARCHAR(36) NOT NULL, quantity INT NOT NULL, operation VARCHAR(50) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reservation_id VARCHAR(36) DEFAULT NULL, metadata JSON DEFAULT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException('This baseline migration cannot be safely reverted without data loss.');
    }
}
